
@baseUrl=http://localhost:3001
###
GET {{baseUrl}}/user/all

###
GET {{baseUrl}}/user/1

###
POST {{baseUrl}}/user
Content-Type: application/json

{
	"firstName": "Samaksh",
	"lastName": "Grover",
	"companyName": "meta"
}

###
PATCH {{baseUrl}}/user
Content-Type: application/json

{
	"id": 1,
	"companyName": "google"
}

###
DELETE {{baseUrl}}/user/1

###
GET {{baseUrl}}/company/all

###
GET {{baseUrl}}/company/2

###
POST {{baseUrl}}/company
Content-Type: application/json

{
	"name": "google",
	"license": "some_random_number",
	"address": "dfkshfkjsjkd"
}

###
PATCH {{baseUrl}}/company
Content-Type: application/json

{
	"id": 2,
	"name": "meta"
}

###
DELETE {{baseUrl}}/company/1


